# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 12:00
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('kon', 'Open Soucre'), ('lek', 'Социальный'), ('hak', 'Коммерческий')], default='hak', max_length=100, verbose_name='Вид проекта')),
                ('img', stdimage.models.StdImageField(null=True, upload_to=apps.projects.models.avatar_path, validators=[stdimage.validators.MaxSizeValidator(1028, 768)], verbose_name='Аватар')),
                ('city', models.CharField(choices=[('msk', 'Москва'), ('spb', 'Санкт-петербург'), ('mhk', 'Махачкала'), ('mhk', 'Каспийск'), ('drb', 'Дербент'), ('kzl', 'Кизляр'), ('hsv', 'Хасавюрт')], default='msk', max_length=100, verbose_name='Город')),
                ('about', models.TextField(max_length=2000, verbose_name='Описание')),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('vk', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
